### ISSUE TITLE
retrieveServiceConfigs behaviour clarification

### ISSUE THREAD

**Issue by shroffk** [epics-base/masarService#18]
```
structure 
    string function retrieveServiceConfigs
    string system all
    string configname LTB2 (all)
```
The following request returns all configurations with system "all" irrespective of the configname.

**Comment by mdavidsaver** [comment]
try 14ac88206dd6e78e2e30f241dfea13225211e49a

**Comment by mdavidsaver** [comment]
ping

**Comment by shroffk** [comment]
@mdavidsaver still resolving some ui things...will test this today

**Comment by shroffk** [comment]
tested out the new masar additions
search based on config name does work indeed when using egit

however my clients request parameters are not up to the mark for the minimasar.ops ☺ 
The request is as described above..

**Comment by shroffk** [comment]
Resolved with the use of the new structure 

```
structure 
    string function retrieveServiceConfigs
    string[] names [system, configname]
    string[] value [all, LTB2 (all)]
```
