### ISSUE TITLE
retriveServiceEvents within a specified time

### ISSUE THREAD

**Issue by shroffk** [epics-base/masarService#19]
Searching for service events with the comment criteria set of **, returns a list of service events while ignoring the start and end times specified.

```
DEBUG:p4p.rpc:RPC reply 
<Value: [('function', u'retrieveServiceEvents'), 
	       ('name', [u'comment', u'user', u'start', u'end']),
               ('value', [u'**', u'*', u'2017-04-02 04:00:00', u'2017-04-05 04:00:00'])]>

-> 
<Value: 
[('labels', [u'event_id', u'config_id', u'comments', u'event_time', u'user_name']), 
 ('value', [('event_id', array([ 8, 49], dtype=int32)), 
               ('config_id', array([11, 27], dtype=int32)),
               ('comments', [u'nnnnnnnnnnnnnnnnn', u'a new snapshot']), 
               ('event_time', [u'2017-04-04 19:16:29', u'2017-04-06 14:21:17']),
               ('user_name', [u'Kunal Shroff', u'Kunal Shroff'])]), 
('descriptor', u''), 
('alarm', [('severity', 0), ('status', 0), ('message', u'')]),
('timeStamp', [('secondsPastEpoch', 0L), ('nanoseconds', 0), ('userTag', 0)])]>
```

**Comment by shroffk** [comment]
A similar query with the search defined based on user=** returns no responses...when the expected response is 1 (refer to above result)

```
DEBUG:p4p.rpc:RPC reply 
<Value: [('function', u'retrieveServiceEvents'), 
              ('name', [u'comment', u'user', u'start', u'end']),
              ('value', [u'*', u'**', u'2017-04-02 04:00:00', u'2017-04-05 04:00:00'])]>
-> 
<Value: 
[('labels', [u'event_id', u'config_id', u'comments', u'event_time', u'user_name']), 
 ('value', [('event_id', array([], dtype=int32)), 
               ('config_id', array([], dtype=int32)),
               ('comments', []), 
               ('event_time', []), 
               ('user_name', [])]), 
('descriptor', u''), 
('alarm', [('severity', 0), ('status', 0), ('message', u'')]),
('timeStamp', [('secondsPastEpoch', 0L), ('nanoseconds', 0), ('userTag', 0)])]>
```

**Comment by shroffk** [comment]
got the same behaviour from the eget client call (guess my request isn't crap then :) )

```
✘ train@training  ~/EPICS-CPP-4.6.0/pvAccessCPP/bin/linux-x86_64  ./eget -s masarService:retrieveServiceEvents -a comment=nnnn
             event_id            config_id             comments           event_time            user_name
                    8                   11    nnnnnnnnnnnnnnnnn  2017-04-04 19:16:29         Kunal Shroff
                   49                   27       a new snapshot  2017-04-06 14:21:17         Kunal Shroff

```

**Comment by mdavidsaver** [comment]
The requests look fine this time ;)  The start= and end= filters are currently ignored as I wasn't sure if this feature was used.  Should I implement this?  How do you expect this to behave?  ```eventtime>=start && eventime<end``` where the default start=0 and end=now

> u'**'

How does u'*' differ from u'**'?  An extra wild wildcard?

**Comment by mdavidsaver** [comment]
I think that previously, u'*' and u'**' were equivalent.  Do you intend to make use of wildcard matching in more complex situation (other than '*' and exact string)?

**Comment by shroffk** [comment]
> eventtime>=start && eventime<end where the default start=0 and end=now

Yes this seems fine to me.

**Comment by shroffk** [comment]
> I think that previously, u'' and u'**' were equivalent. 

I think that is fine '' being equivalent to "*" or "**"

>Do you intend to make use of wildcard matching in more complex situation (other than '' and exact string)?

Regarding wildcards I think it would be fine to support the basic use of it.
string = test, it should match \*test\*, \*t\*t\*, \*te\*

**Comment by shengb** [comment]
I think the original design/implementation support wildcard matching, which means "*" to multiple characters and "?" for single character.
Therefore, u'*' == u'**'. 
But I cannot remember exactly.

Any use case for u''?

**Comment by mdavidsaver** [comment]
fa72a767038d91e9d760a643611fbc8dd7973526 looks for start= and end= with retrieveServiceEvents(), but not retrieveSnapshot() where it doesn't seem useful (unless I hear otherwise).

65b2993eb87c4a8abc591711cba5f269bddf7013 replaces use of sql 'like' with sqlite3 'glob' operator, which should give the desired behavior.

**Comment by shroffk** [comment]
The start and the end now work.

**Comment by mdavidsaver** [comment]
How about the wildcard matching change?

**Comment by mdavidsaver** [comment]
@shroffk  ping

**Comment by shroffk** [comment]
```
./eget -s masarService:retrieveServiceEvents -a comment="*one*" 
               event_id              config_id               comments             event_time              user_name
                      2                      1  saving first snapshot    2017-05-01 15:53:11           Kunal Shroff
                      7                      1            one percent    2017-05-02 13:13:06           Kunal Shroff
                      9                      1            one-percent    2017-05-02 13:15:27           Kunal Shroff
                      6                      2         a new snapshot    2017-05-01 18:48:56           Kunal Shroff
                     11                      3         third snapshot    2017-05-02 13:18:51           Kunal Shroff
                     14                      4      with a missing pv    2017-05-02 13:36:04           Kunal Shroff
```

**Comment by mdavidsaver** [comment]
Added wildcard filtering on 'comment' w/ 85231f6ac7f9d6168ff65bda663a15baff4f7909.

Note that I've rewritten history on this branch to cleanup in preparation for merging.  This should be the last/only time.

**Comment by shroffk** [comment]
checked out the latest master unfortunately could not search by comment.
```
./eget -s masarService:retrieveServiceEvents           
             event_id            config_id             comments           event_time            user_name
                    2                    1      first snampshot  2017-05-30 18:58:09         Kunal Shroff
                    3                    1          second.....  2017-05-30 18:59:30         Kunal Shroff
```

**Comment by mdavidsaver** [comment]
Glob matching is done by applying the pattern to the entire field.  Therefore the pattern "first" will only match the exact string "field".  What I think you want to match on is "first*" or "*first*" which should match only one of the two events in your example.

**Comment by shroffk** [comment]
I assumed the search string was being padded at the end with a \*
